# Định nghĩa cổng chạy dịch vụ
server:
  port: 8083

spring:
  application:
    name: supplier-service # Đổi tên định danh cho service

  datasource:
    # 1. Thông tin cơ bản (Nguyên lý: Database per Service)
    url: jdbc:postgresql://localhost:5434/supplier-db?currentSchema=public
    username: postgres
    password: K59Ptl*100504
    driver-class-name: org.postgresql.Driver
  # 2. Cấu hình Hikari Connection Pool (Tối ưu cho Production)
  hikari:
    pool-name: HikariPool-UserService # Đổi tên pool để dễ trace log
    maximum-pool-size: 10 # Số lượng connection tối đa
    minimum-idle: 5       # Số lượng connection nhàn rỗi tối thiểu
    idle-timeout: 300000  # 5 phút (ms)
    max-lifetime: 1800000 # 30 phút (ms)
    connection-timeout: 20000 # Thời gian chờ kết nối trước khi báo lỗi (20s)

  liquibase:
    enabled: false
    # File tổng quản lý tất cả các file thay đổi con
    change-log: classpath:liquibase/master.xml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # 3. Cấu hình Hibernate
    hibernate:
      # validate: Kiểm tra schema DB với Entity (Khuyên dùng cho Prod)
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: false # Tắt log SQL ở Prod để tránh lộ dữ liệu/giảm hiệu năng
    properties:
      hibernate:
        format_sql: true
        # Giúp tránh lỗi N+1 và tối ưu fetch data
        default_batch_fetch_size: 20
  # 4. Quản lý lỗi kết nối
  sql:
    init:
      continue-on-error: false