apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: periodic-payment
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "K59Ptl*100504"
  JWT_SECRET: "your-jwt-secret-key-change-this-in-production"
